name = "DyadCommunityRegistry"
uuid = "6b89d7c0-51a9-4e04-8883-3c89c4a310e3"
repo = "https://github.com/DyadLang/DyadCommunityRegistry"
description = "An open community registry for Dyad-related packages"

[packages]
8c5872ae-171c-4c52-b73c-5e25d4616bb7 = { name = "SpacePowerWorkshop", path = "S/SpacePowerWorkshop" }
